name: Religion
main: Lihad.Religion.Religion
version: 1.14
commands:
  rr:
    description: Invalid Command
    usage: Invalid Command
  overt:
    description: Invalid Command
    usage: Invalid Command